# -*- coding: utf-8 -*-
"""sprint1-roseplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12atKIceFJWCcw2j21BOcf32KJPdldBrc
"""

# ============================================================================
# SETUP AND IMPORTS
# ============================================================================

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from transformers import pipeline
import warnings
warnings.filterwarnings('ignore')
from google.colab import drive   # Delete these two lines - only a package on google colab
drive.mount('/content/drive')    # Delete these two lines - only a package on google colab

sentiment_analyzer = pipeline("sentiment-analysis",
                             model="cardiffnlp/twitter-roberta-base-sentiment-latest")

print("Setup complete!\n")

# ============================================================================
# DATA LOADING AND PREPROCESSING
# ============================================================================

print("Loading data...")
df = pd.read_csv("/content/drive/My Drive/ColabNotebooks/Capstone/data/Merged Goal Intervention long - BRIGHTS.csv") # You will need to change this to the data source
print(f"   Loaded {len(df)} participants\n")

# Define target questions
question_labels = {
    'Q39': 'Progress toward goal',
    'Q40': 'Confidence in achieving goal',
    'Q41': 'Goal importance'
}

print("Processing Q39, Q40, Q41 for GT2-6...")

# Convert questions to numeric
for t in range(2, 7):
    for q in [39, 40, 41]:
        col = f'GT{t}Q{q}'
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

# Create mean scores for each timepoint
for t in range(2, 7):
    cols = [f'GT{t}Q{q}' for q in [39, 40, 41] if f'GT{t}Q{q}' in df.columns]
    if cols:
        df[f'GT{t}_Likert_Mean'] = df[cols].mean(axis=1)

print("Likert scores calculated\n")

# Sentiment analysis
print("Running sentiment analysis...")

goal_text_cols = []
for t in range(1, 7):
    for possible_col in [f'T{t}_GoalText', f'GoalT{t}']:
        if possible_col in df.columns:
            goal_text_cols.append(possible_col)
            break

sentiment_map = {'negative': -1, 'neutral': 0, 'positive': 1}

for col in goal_text_cols:
    goals = df[col].fillna('').tolist()
    sentiments = []
    numerics = []

    for goal in goals:
        if goal and len(str(goal).strip()) > 0:
            result = sentiment_analyzer(str(goal)[:512])[0]
            sentiment_label = result['label'].lower()
            sentiments.append(sentiment_label)
            numerics.append(sentiment_map.get(sentiment_label, 0))
        else:
            sentiments.append(np.nan)
            numerics.append(np.nan)

    df[f'{col}_Sentiment'] = sentiments
    df[f'{col}_Sentiment_Numeric'] = numerics

print("Sentiment analysis complete\n")

# Select user
print("Selecting user for visualization...")

# MANUALLY SET USER ID HERE:
user_id = '0019A30A1F2C41C685A9CE494181EED2'  # WILL NEED TO BECOME THE USERS' LOGIN

# Find the user's data (FIXED)
id_col = 'StudyID' if 'StudyID' in df.columns else 'ParticipantID' if 'ParticipantID' in df.columns else None

if id_col:
    user_rows = df[df[id_col] == user_id]
else:
    user_rows = df[df.index == user_id]

if len(user_rows) == 0:
    print(f"User {user_id} not found, using first participant")
    user_data = df.iloc[0]
    user_id = user_data.get('StudyID', user_data.get('ParticipantID', 'User_0'))
else:
    user_data = user_rows.iloc[0]

print(f"Selected user: {user_id}\n")
print("="*80)
print(f"GOAL PROGRESSION ANALYSIS: {user_id}")
print("="*80)

# ============================================================================
# DISPLAY USER'S GOALS
# ============================================================================

print("\nUSER'S GOALS ACROSS TIMEPOINTS")
print("="*80)

for t in range(1, 7):
    goal = None
    sentiment = None

    # Get goal text
    for col in [f'T{t}_GoalText', f'GoalT{t}']:
        if col in user_data.index and pd.notna(user_data.get(col)):
            goal = user_data[col]
            break

    # Get sentiment
    for col in [f'T{t}_GoalText_Sentiment', f'GoalT{t}_Sentiment']:
        if col in user_data.index:
            sentiment = user_data.get(col)
            break

    # Get Likert scores for Q39, Q40, Q41 (T2-6 only)
    likert_info = ""
    if t >= 2:
        scores = []
        for q_key, q_label in question_labels.items():
            q_num = int(q_key[1:])
            col = f'GT{t}Q{q_num}'
            if col in user_data.index:
                score = user_data.get(col)
                if not pd.isna(score):
                    scores.append(f"{q_key}: {score}/7")
        if scores:
            likert_info = f"\n    Scores: {', '.join(scores)}"

    if goal:
        print(f"\nT{t}: {goal}")
        if sentiment:
            print(f"    Sentiment: {sentiment.capitalize()}{likert_info}")
        else:
            print(f"    Sentiment: N/A{likert_info}")

print("\n" + "="*80)
print()

# ============================================================================
# VISUALIZATION 4: 6x3 ROSE PLOT GRID WITH LIKERT LABELS
# ============================================================================

print("\nCreating 6x3 rose plot grid...")

# Define Likert scale labels
likert_labels = {
    1: 'Strongly<br>disagree',
    2: 'Disagree',
    3: 'Somewhat<br>disagree',
    4: 'Neutral',
    5: 'Somewhat<br>agree',
    6: 'Agree',
    7: 'Strongly<br>agree'
}

# Collect data for all three questions across timepoints
rose_data = []

for t in range(2, 7):
    for q_key, q_label in question_labels.items():
        q_num = int(q_key[1:])
        col_name = f'GT{t}Q{q_num}'

        if col_name in user_data.index:
            score = user_data.get(col_name)
            if not pd.isna(score):
                rose_data.append({
                    'Timepoint': t,
                    'Question': q_label,
                    'Q_Code': q_key,
                    'Score': int(score)
                })

if len(rose_data) >= 9:
    rose_df = pd.DataFrame(rose_data)

    # Create subplot with 6 rows x 3 columns
    from plotly.subplots import make_subplots

    # Create combined subplot titles (T#: Question)
    subplot_titles = []
    for t in range(2, 7):
        for q in question_labels.values():
            subplot_titles.append(f"<b>T{t}: {q}</b>")
    # Add summary row titles
    for q in question_labels.values():
        subplot_titles.append(f"<b>All T2-T6: {q}</b>")

    fig_grid = make_subplots(
        rows=6, cols=3,
        specs=[[{'type': 'polar'}]*3 for _ in range(6)],
        subplot_titles=subplot_titles,
        vertical_spacing=0.10,  # More spacing for longer titles
        horizontal_spacing=0.05
    )

    # Color for each score level
    score_colors = {
        1: '#d73027',
        2: '#fc8d59',
        3: '#fee090',
        4: '#e0e0e0',
        5: '#91bfdb',
        6: '#4575b4',
        7: '#2166AC'
    }

    # Calculate angle - UPWARD FACING
    def score_to_angle(score):
        return (score - 1) * 30

    # Create plots for each timepoint (rows 1-5)
    for row_idx, t in enumerate(range(2, 7), start=1):
        for col_idx, (q_key, q_label) in enumerate(question_labels.items(), start=1):
            score_data = rose_df[(rose_df['Timepoint'] == t) & (rose_df['Question'] == q_label)]

            if len(score_data) > 0:
                score = score_data.iloc[0]['Score']
                angle = score_to_angle(score)
                color = score_colors[score]

                fig_grid.add_trace(
                    go.Barpolar(
                        r=[1],
                        theta=[angle],
                        width=25,
                        marker=dict(
                            color=color,
                            line=dict(color='white', width=2),
                            opacity=0.9
                        ),
                        hovertext=f"T{t}: {likert_labels[score].replace('<br>', ' ')}",
                        hoverinfo='text',
                        showlegend=False
                    ),
                    row=row_idx, col=col_idx
                )

    # Create summary plots (row 6)
    for col_idx, (q_key, q_label) in enumerate(question_labels.items(), start=1):
        q_data = rose_df[rose_df['Question'] == q_label]

        if len(q_data) > 0:
            score_counts = q_data['Score'].value_counts()
            max_count = score_counts.max()

            for score, count in score_counts.items():
                angle = score_to_angle(score)
                color = score_colors[score]
                height = (count / max_count) ** 0.5

                fig_grid.add_trace(
                    go.Barpolar(
                        r=[height],
                        theta=[angle],
                        width=25,
                        marker=dict(
                            color=color,
                            line=dict(color='white', width=2),
                            opacity=0.9
                        ),
                        hovertext=f"{likert_labels[score].replace('<br>', ' ')}: {count}/{len(q_data)} times ({count/len(q_data)*100:.0f}%)",
                        hoverinfo='text',
                        showlegend=False
                    ),
                    row=6, col=col_idx
                )

    # Update all polar subplots
    for row in range(1, 7):
        for col in range(1, 4):
            fig_grid.update_polars(
                radialaxis=dict(
                    range=[0, 1.3],
                    showticklabels=False,
                    showline=False,
                    gridcolor='lightgray',
                    gridwidth=1
                ),
                angularaxis=dict(
                    direction='clockwise',
                    rotation=180,
                    tickmode='array',
                    tickvals=[0, 30, 60, 90, 120, 150, 180],
                    ticktext=[
                        likert_labels[1],
                        likert_labels[2],
                        likert_labels[3],
                        likert_labels[4],
                        likert_labels[5],
                        likert_labels[6],
                        likert_labels[7]
                    ],
                    showline=False,
                    gridcolor='lightgray',
                    tickfont=dict(size=9)
                ),
                bgcolor='rgba(255, 255, 255, 0)',
                row=row, col=col
            )

    fig_grid.update_layout(
        title=dict(
            text="<b>Goal Progression Journey (T2 - T6)</b><br><sub>Individual responses by timepoint and question</sub>",
            x=0.5,
            xanchor='center',
            font=dict(size=20)
        ),
        height=2400,
        width=1800,
        paper_bgcolor='white',
        showlegend=False,
        margin=dict(t=120, l=120, r=120, b=120)
    )

    for annotation in fig_grid['layout']['annotations']:
        # Only move the subplot titles, not the main title
        if any(keyword in annotation['text'] for keyword in ['T2:', 'T3:', 'T4:', 'T5:', 'T6:', 'All T2-T6:']):
            annotation['y'] = annotation['y'] - 0.095  # Adjust this number to move titles up/down
    fig_grid.show()
    print("6x3 rose plot grid created!")

    # Print detailed summary
    print(f"\nDetailed Question Analysis:")
    for q_label in question_labels.values():
        q_data = rose_df[rose_df['Question'] == q_label].sort_values('Timepoint')
        if len(q_data) > 0:
            print(f"\n{q_label}:")
            for _, row in q_data.iterrows():
                score = int(row['Score'])
                label = likert_labels[score].replace('<br>', ' ')
                print(f"   T{int(row['Timepoint'])}: {score} ({label})")

            score_counts = q_data['Score'].value_counts().sort_index()
            print(f"   Distribution across T2-T6:")
            for score, count in score_counts.items():
                label = likert_labels[score].replace('<br>', ' ')
                print(f"      {label}: {count} times")
else:
    print("Insufficient data for rose plots")

print("\n" + "="*80)
print("ALL VISUALIZATIONS COMPLETE!")
print("="*80)
