/* Shared style objects for admin page components. */
export const adminStyles = {
  tabContent: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },

  subTabBar: {
    display: "flex",
    gap: 6,
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 4,
  },
  subTabBtn: {
    padding: "6px 14px",
    borderRadius: 999,
    border: "1px solid var(--ghost-border)",
    background: "var(--ghost-bg)",
    color: "var(--ghost-color)",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: 12,
  },
  subTabBtnActive: {
    background: "#7b9eff22",
    border: "1px solid #7b9eff",
    color: "var(--text-primary)",
  },

  filterRow: {
    display: "flex",
    gap: 12,
    alignItems: "flex-end",
    flexWrap: "wrap",
  },
  filterLabel: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    fontWeight: 800,
    fontSize: 12,
    color: "var(--text-dim)",
  },

  select: {
    padding: "9px 11px",
    borderRadius: 10,
    border: "1px solid var(--ghost-border)",
    background: "var(--ghost-bg)",
    color: "var(--ghost-color)",
    outline: "none",
    fontSize: 13,
  },

  searchInputWrap: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchInput: {
    padding: "9px 32px 9px 11px",
    borderRadius: 10,
    border: "1px solid var(--ghost-border)",
    background: "var(--ghost-bg)",
    color: "var(--ghost-color)",
    outline: "none",
    fontSize: 13,
    width: 200,
  },
  clearBtn: {
    position: "absolute",
    right: 8,
    background: "none",
    border: "none",
    color: "var(--text-dim)",
    cursor: "pointer",
    fontSize: 16,
    lineHeight: 1,
    padding: 0,
  },
  searchDropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    zIndex: 100,
    background: "var(--card-bg)",
    border: "1px solid var(--card-border)",
    borderRadius: 10,
    boxShadow: "0 8px 24px rgba(0,0,0,0.25)",
    overflow: "hidden",
    overflowY: "auto",
    maxHeight: 280,
    marginTop: 2,
  },
  searchOption: {
    padding: "9px 12px",
    cursor: "pointer",
    fontSize: 13,
    display: "flex",
    alignItems: "center",
    color: "var(--text-primary)",
    transition: "background 0.1s",
  },
  searchOptionActive: {
    background: "#7b9eff18",
    color: "var(--text-primary)",
  },
  roleTag: {
    marginLeft: "auto",
    fontSize: 10,
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: 999,
    background: "#7b9eff22",
    border: "1px solid #7b9eff44",
    color: "#7b9eff",
  },

  sectionBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 800,
    color: "var(--text-primary)",
  },
  sectionSubtitle: {
    margin: 0,
    fontSize: 13,
    color: "var(--text-dim)",
  },

  plotWrap: {
    borderRadius: 12,
    border: "1px solid var(--subtle-border)",
    background: "var(--surface-subtle)",
    padding: 12,
  },

  statGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: 12,
  },
  statCard: {
    padding: "16px 14px",
    borderRadius: 12,
    border: "1px solid var(--card-border)",
    background: "var(--surface-subtle)",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  statCardWarn: {
    border: "1px solid #ffb4b455",
    background: "#ffb4b408",
  },
  statValue: {
    fontSize: 26,
    fontWeight: 900,
    color: "var(--text-primary)",
    lineHeight: 1,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-dim)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },

  sectionHeading: {
    fontWeight: 800,
    fontSize: 14,
    color: "var(--text-dim)",
    margin: "8px 0 4px",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },

  tableWrap: {
    overflowX: "auto",
    borderRadius: 10,
    border: "1px solid var(--subtle-border)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
  },
  th: {
    padding: "9px 12px",
    textAlign: "left",
    fontWeight: 800,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--text-dim)",
    background: "var(--surface-subtle)",
    borderBottom: "1px solid var(--subtle-border)",
    whiteSpace: "nowrap",
  },
  tr: {
    borderBottom: "1px solid var(--subtle-border)",
  },
  td: {
    padding: "9px 12px",
    color: "var(--text-primary)",
    verticalAlign: "top",
  },

  eventBadge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    background: "var(--surface-subtle)",
    border: "1px solid var(--subtle-border)",
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
  },
  eventBadgeWarn: {
    background: "#ffb4b415",
    border: "1px solid #ffb4b455",
    color: "#ffb4b4",
  },

  pagination: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 8,
  },
  pageBtn: {
    padding: "7px 14px",
    borderRadius: 8,
    border: "1px solid var(--ghost-border)",
    background: "var(--ghost-bg)",
    color: "var(--ghost-color)",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: 13,
  },
  pageInfo: {
    fontSize: 13,
    color: "var(--text-dim)",
  },

  questionList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  questionRow: {
    display: "flex",
    gap: 12,
    alignItems: "flex-start",
    padding: "12px 14px",
    borderRadius: 10,
    border: "1px solid var(--subtle-border)",
    background: "var(--surface-subtle)",
  },
  questionRowInactive: {
    opacity: 0.45,
  },
  questionMeta: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    minWidth: 36,
    paddingTop: 2,
  },
  questionNum: {
    fontWeight: 900,
    fontSize: 12,
    color: "var(--text-dim)",
  },
  inactiveTag: {
    fontSize: 9,
    fontWeight: 700,
    padding: "1px 5px",
    borderRadius: 999,
    background: "#ffb4b420",
    color: "#ffb4b4",
    border: "1px solid #ffb4b440",
    whiteSpace: "nowrap",
  },
  questionText: {
    flex: 1,
    fontSize: 13,
    color: "var(--text-primary)",
    lineHeight: 1.5,
  },
  questionActions: {
    display: "flex",
    gap: 6,
    flexShrink: 0,
    flexWrap: "wrap",
  },

  editTextarea: {
    width: "100%",
    padding: "9px 11px",
    borderRadius: 10,
    border: "1px solid var(--input-border)",
    background: "var(--input-bg)",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.5,
    resize: "vertical",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },

  addForm: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "16px 14px",
    borderRadius: 10,
    border: "1px solid var(--subtle-border)",
    background: "var(--surface-subtle)",
    marginTop: 8,
  },

  btnPrimary: {
    padding: "9px 18px",
    borderRadius: 10,
    border: "none",
    background: "#7b9eff",
    color: "#fff",
    fontWeight: 800,
    fontSize: 13,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  btnGhost: {
    padding: "7px 12px",
    borderRadius: 8,
    border: "1px solid var(--ghost-border)",
    background: "var(--ghost-bg)",
    color: "var(--ghost-color)",
    fontWeight: 700,
    fontSize: 12,
    cursor: "pointer",
  },

  pillBtn: {
    padding: "8px 12px",
    borderRadius: 12,
    border: "1px solid var(--ghost-border)",
    background: "var(--ghost-bg)",
    color: "var(--ghost-color)",
    fontWeight: 900,
    textDecoration: "none",
    fontSize: 13,
  },

  errorText: {
    padding: "10px 12px",
    color: "#ffb4b4",
    fontWeight: 700,
    fontSize: 13,
  },

  loading: {
    padding: 16,
    opacity: 0.55,
    fontSize: 13,
  },
};
