# -*- coding: utf-8 -*-
"""solodivergingstackedbarchart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uk7Pb6vm1GNnLEZJI-57-d-rKa-Fp8B8
"""

# analysis/solodivergingstackedbarchart.py

import sqlalchemy
import plotly.graph_objects as go
import pandas as pd
import numpy as np


def fetch_data(participant_id, engine):
    """
    participant_id : str              — the logged-in user's study ID
    engine         : sqlalchemy Engine — injected by the backend

    Returns a pandas DataFrame with all Likert responses for this user,
    or None if no data exists.
    """
    query = sqlalchemy.text("""
        SELECT *
        FROM "BRIGHTS"
        WHERE "ID" = :pid
        LIMIT 1
    """)
    with engine.connect() as conn:
        result = conn.execute(query, {"pid": participant_id})
        rows = result.fetchall()
        if not rows:
            return None
        columns = result.keys()
        return pd.DataFrame(rows, columns=columns)


def create_figure(participant_id, engine):
    """
    Main entry point called by the backend.
    Returns a Plotly figure dict, or a dict with an 'error' key.
    """
    df = fetch_data(participant_id, engine)
    if df is None or df.empty:
        return {"error": f"No data found for participant {participant_id}"}

    user_data = df.iloc[0]

    # ── Question metadata ─────────────────────────────────────────────────────
    QUESTION_META = {
        1:  ('Centrality – Current',                'Identity & Centrality'),
        2:  ('Centrality – Ideal',                  'Identity & Centrality'),
        3:  ('Centrality – Ought',                  'Identity & Centrality'),
        4:  ('Values alignment',                    'Values & Meaning'),
        5:  ('Patience – Calm pursuit',             'Goals-Based Patience'),
        6:  ('Patience – Tolerates challenges',     'Goals-Based Patience'),
        7:  ('Patience – Patient pursuit',          'Goals-Based Patience'),
        8:  ('Patience – Emotion regulation',       'Goals-Based Patience'),
        9:  ("Patience – Doesn't lose cool",        'Goals-Based Patience'),
        10: ('Patience – Controls neg. feelings',   'Goals-Based Patience'),
        11: ('Meaning – Part of meaningful life',   'Values & Meaning'),
        12: ('Meaning – Sense of meaning',          'Values & Meaning'),
        13: ('Meaning – Crucial for meaning',       'Values & Meaning'),
        14: ('Motivation – External',               'Motivation'),
        15: ('Motivation – Introjected',            'Motivation'),
        16: ('Motivation – Integrated',             'Motivation'),
        17: ('Motivation – Intrinsic',              'Motivation'),
        18: ('Integrative ER – Understand why',     'Emotion Regulation'),
        19: ('Integrative ER – Observe emotions',   'Emotion Regulation'),
        20: ('Suppressive ER – Hide feelings',      'Emotion Regulation'),
        21: ('Suppressive ER – Keep to self',       'Emotion Regulation'),
        22: ('Suppressive ER – Control/suppress',   'Emotion Regulation'),
        23: ('Identity – Core aspect',              'Identity & Centrality'),
        24: ('Identity – Reflection of self',       'Identity & Centrality'),
        25: ('Identity – Sense of self',            'Identity & Centrality'),
        26: ('Self-Worth↑ – Esteem boost',          'Contingent Self-Worth'),
        27: ('Self-Worth↑ – Feel worthwhile',       'Contingent Self-Worth'),
        28: ('Self-Worth↑ – Feel good',             'Contingent Self-Worth'),
        29: ('Self-Worth↑ – Worth goes up',         'Contingent Self-Worth'),
        30: ('Self-Worth↓ – Worth suffers',         'Contingent Self-Worth'),
        31: ('Self-Worth↓ – Esteem goes down',      'Contingent Self-Worth'),
        32: ('Self-Worth↓ – Feel bad',              'Contingent Self-Worth'),
        33: ('Self-Worth↓ – Worth goes down',       'Contingent Self-Worth'),
        34: ('Courage – Courageous pursuit',        'Goals-Based Courage'),
        35: ('Courage – Overcomes anxiety',         'Goals-Based Courage'),
        36: ('Courage – Beyond fears',              'Goals-Based Courage'),
        37: ('Courage – Pursues when risky',        'Goals-Based Courage'),
        38: ('Courage – Pursues despite threats',   'Goals-Based Courage'),
        39: ('Progress – Made a lot of progress',   'Goal Progress'),
        40: ('Progress – On track with plan',       'Goal Progress'),
        41: ('Progress – Close to achieving',       'Goal Progress'),
        42: ('Accountability – Human',              'Accountability'),
        43: ('Accountability – Transcendent',       'Accountability'),
    }

    CATEGORY_ORDER = [
        'Identity & Centrality',
        'Values & Meaning',
        'Goals-Based Patience',
        'Motivation',
        'Emotion Regulation',
        'Contingent Self-Worth',
        'Goals-Based Courage',
        'Goal Progress',
        'Accountability',
    ]

    TIMEPOINTS  = [1, 2, 3, 4, 5, 6]
    WEEK_LABELS = {t: f'Week {t}' for t in TIMEPOINTS}

    colors = {
        1: '#d7191c', 2: '#fdae61', 3: '#ffffbf',
        4: '#e0e0e0',
        5: '#a6d96a', 6: '#1a9641', 7: '#006837'
    }
    legend_labels = {
        1: '1 – Strongly disagree', 2: '2 – Disagree',
        3: '3 – Somewhat disagree', 4: '4 – Neutral',
        5: '5 – Somewhat agree',    6: '6 – Agree',
        7: '7 – Strongly agree'
    }
    tick_labels_map = {
        1: 'Strongly<br>disagree (1)', 2: 'Disagree<br>(2)',
        3: 'Somewhat<br>disagree (3)', 4: 'Neutral<br>(4)',
        5: 'Somewhat<br>agree (5)',    6: 'Agree<br>(6)',
        7: 'Strongly<br>agree (7)'
    }

    col_width   = 1.0
    col_centers = {r: float(r) for r in range(1, 8)}

    # ── Build y-axis row order with category header spacers ───────────────────
    y_order              = []
    category_header_rows = {}
    category_data_rows   = {}

    for cat in CATEGORY_ORDER:
        cat_qs     = sorted([q for q, (_, c) in QUESTION_META.items() if c == cat])
        header_key = f'── {cat} ──'
        y_order.append(header_key)
        category_header_rows[cat] = header_key
        category_data_rows[cat]   = []
        for q_num in cat_qs:
            q_label, _ = QUESTION_META[q_num]
            y_key = f'Q{q_num}: {q_label}'
            y_order.append(y_key)
            category_data_rows[cat].append(y_key)

    y_order_reversed = list(reversed(y_order))

    # ── Collect responses from user row ───────────────────────────────────────
    all_records = []
    for t in TIMEPOINTS:
        for q_num, (q_label, cat) in QUESTION_META.items():
            col_name = f'T{t}_Q{q_num}'
            if col_name not in df.columns:
                continue
            val = user_data.get(col_name, float('nan'))
            try:
                if pd.isna(val):
                    continue
            except (TypeError, ValueError):
                continue
            all_records.append({
                'y_key':     f'Q{q_num}: {q_label}',
                'timepoint': t,
                'week':      WEEK_LABELS[t],
                'Question':  q_label,
                'Category':  cat,
                'Response':  int(val),
            })

    if not all_records:
        return {"error": "No Likert responses found for this participant"}

    rec_df = pd.DataFrame(all_records)

    # ── Precompute week-over-week deltas ──────────────────────────────────────
    delta_map = {}
    for t in TIMEPOINTS:
        for q_num, (q_label, _) in QUESTION_META.items():
            y_key    = f'Q{q_num}: {q_label}'
            curr_col = f'T{t}_Q{q_num}'
            prev_col = f'T{t-1}_Q{q_num}' if t > TIMEPOINTS[0] else None

            curr_val = user_data.get(curr_col, float('nan')) if curr_col in df.columns else float('nan')
            prev_val = user_data.get(prev_col, float('nan')) if (prev_col and prev_col in df.columns) else float('nan')

            try:
                curr_nan = pd.isna(curr_val)
                prev_nan = pd.isna(prev_val)
            except (TypeError, ValueError):
                curr_nan = prev_nan = True

            if not curr_nan and not prev_nan:
                delta_map[(t, y_key)] = int(curr_val) - int(prev_val)
            else:
                delta_map[(t, y_key)] = None

    def delta_label(d):
        if d is None or d == 0:
            return None
        return f'▲ +{d}' if d > 0 else f'▼ {d}'

    def delta_color(d):
        if d is None or d == 0:
            return None
        return '#1a7a1a' if d > 0 else '#cc2200'

    # ── Build bar traces ──────────────────────────────────────────────────────
    fig          = go.Figure()
    legend_added = set()

    for t in TIMEPOINTS:
        t_df = rec_df[rec_df['timepoint'] == t]

        for r_val in range(1, 8):
            r_df = t_df[t_df['Response'] == r_val]

            show_legend = (t == TIMEPOINTS[0]) and (r_val not in legend_added)
            if show_legend:
                legend_added.add(r_val)

            y_vals, x_vals, base_vals, text_vals, hover_vals = [], [], [], [], []

            for y_key in y_order:
                if y_key.startswith('──'):
                    y_vals.append(y_key)
                    x_vals.append(0)
                    base_vals.append(col_centers[r_val] - col_width / 2)
                    text_vals.append('')
                    hover_vals.append('<extra></extra>')
                    continue

                match = r_df[r_df['y_key'] == y_key]
                if not match.empty:
                    row = match.iloc[0]
                    d   = delta_map.get((t, y_key))
                    dl  = delta_label(d)
                    y_vals.append(y_key)
                    x_vals.append(col_width)
                    base_vals.append(col_centers[r_val] - col_width / 2)
                    text_vals.append(str(r_val))
                    hover_vals.append(
                        f"<b>{row['Category']}</b><br>"
                        f"{row['Question']}<br>"
                        f"Timepoint: {WEEK_LABELS[t]}<br>"
                        f"Response: {legend_labels[r_val]}"
                        + (f"<br><b>{dl}</b> vs prior week" if dl else "")
                        + "<extra></extra>"
                    )
                else:
                    y_vals.append(y_key)
                    x_vals.append(0)
                    base_vals.append(col_centers[r_val] - col_width / 2)
                    text_vals.append('')
                    hover_vals.append('<extra></extra>')

            fig.add_trace(go.Bar(
                y=y_vals,
                x=x_vals,
                base=base_vals,
                orientation='h',
                marker=dict(color=colors[r_val], line=dict(width=1, color='white')),
                name=legend_labels[r_val],
                legendgroup=str(r_val),
                showlegend=show_legend,
                text=text_vals,
                textposition='inside',
                insidetextanchor='middle',
                textfont=dict(size=10, color='black'),
                hovertemplate=hover_vals,
                visible=(t == TIMEPOINTS[0]),
            ))

    # ── Delta scatter traces (one per timepoint) ──────────────────────────────
    for t in TIMEPOINTS:
        ann_y, ann_text, ann_colors = [], [], []
        for y_key in y_order:
            if y_key.startswith('──'):
                continue
            d  = delta_map.get((t, y_key))
            dl = delta_label(d)
            if dl:
                ann_y.append(y_key)
                ann_text.append(dl)
                ann_colors.append(delta_color(d))

        fig.add_trace(go.Scatter(
            x=[7.75] * len(ann_y),
            y=ann_y,
            mode='text',
            text=ann_text,
            textfont=dict(size=10, color=ann_colors),
            textposition='middle right',
            showlegend=False,
            hoverinfo='skip',
            visible=(t == TIMEPOINTS[0]),
            name=f'delta_t{t}',
        ))

    # ── Dropdown buttons ──────────────────────────────────────────────────────
    n_response_vals = 7
    n_timepoints    = len(TIMEPOINTS)

    buttons = []
    for ti, t in enumerate(TIMEPOINTS):
        bar_visibility   = [tj == ti for tj in range(n_timepoints) for _ in range(n_response_vals)]
        delta_visibility = [tj == ti for tj in range(n_timepoints)]
        visibility       = bar_visibility + delta_visibility

        buttons.append(dict(
            label=WEEK_LABELS[t],
            method='update',
            args=[
                {'visible': visibility},
                {'title': {
                    'text': (
                        f"<b>Goal Progression Responses — {WEEK_LABELS[t]}</b><br>"
                        "<sub>All Likert Items — Diverging Scale View</sub>"
                    ),
                    'x': 0.5, 'xanchor': 'center',
                    'font': {'size': 16, 'color': '#e9eefc'}
                }}
            ]
        ))

    # ── Zone dividers ─────────────────────────────────────────────────────────
    for x_div in [3.5, 4.5]:
        fig.add_vline(x=x_div, line_color='rgba(200,214,240,0.3)', line_width=1, line_dash='dot')

    # ── Category header tick labels ───────────────────────────────────────────
    all_tick_labels = []
    for y_key in y_order_reversed:
        is_header = any(y_key == hk for hk in category_header_rows.values())
        if is_header:
            clean = y_key.replace('──', '').strip()
            all_tick_labels.append(f'<b>{clean}</b>')
        else:
            all_tick_labels.append(y_key)

    fig.update_layout(
        title=dict(
            text=(
                f"<b>Goal Progression Responses — {WEEK_LABELS[TIMEPOINTS[0]]}</b><br>"
                "<sub>All Likert Items — Diverging Scale View</sub>"
            ),
            x=0.5, xanchor='center',
            font=dict(size=16, color='#e9eefc'),
        ),
        updatemenus=[dict(
            buttons=buttons,
            direction='down',
            showactive=True,
            x=1.01, xanchor='left',
            y=1.08, yanchor='top',
            bgcolor='rgba(30,40,70,0.9)',
            bordercolor='#4a5568',
            font=dict(size=12, color='#e9eefc'),
        )],
        annotations=[
            dict(
                text='Select week:',
                x=1.01, xanchor='left', y=1.13, yanchor='top',
                xref='paper', yref='paper',
                showarrow=False, font=dict(size=12, color='#c8d6f0'),
            ),
            dict(
                text='← Disagree                                        Agree →',
                x=0.5, xanchor='center', y=-0.06, yanchor='top',
                xref='paper', yref='paper',
                showarrow=False, font=dict(size=12, color='#c8d6f0'),
            ),
            dict(
                text='<span style="color:#4ade80">▲ Gained</span>  '
                     '<span style="color:#f87171">▼ Declined</span>  '
                     '<span style="color:#94a3b8">vs. prior week</span>',
                x=0.5, xanchor='center', y=-0.10, yanchor='top',
                xref='paper', yref='paper',
                showarrow=False, font=dict(size=11),
            ),
        ],
        barmode='overlay',
        xaxis=dict(
            title='',
            range=[0.5, 7.5],
            tickvals=[col_centers[r] for r in range(1, 8)],
            ticktext=[tick_labels_map[r] for r in range(1, 8)],
            showgrid=False, zeroline=False,
            tickfont=dict(size=10, color='#c8d6f0'),
        ),
        yaxis=dict(
            categoryorder='array',
            categoryarray=y_order_reversed,
            tickmode='array',
            tickvals=y_order_reversed,
            ticktext=all_tick_labels,
            tickfont=dict(size=9, color='#c8d6f0'),
            autorange=False,
            range=[-0.5, len(y_order) - 0.5],
        ),
        height=max(1200, len(y_order) * 22),
        width=1250,
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        margin=dict(l=260, r=260, t=120, b=130),
        legend=dict(
            title=dict(text='Response', font=dict(color='#c8d6f0')),
            traceorder='normal',
            orientation='v',
            x=1.01, y=0.5,
            xanchor='left', yanchor='middle',
            font=dict(size=11, color='#c8d6f0'),
            bgcolor='rgba(0,0,0,0)',
        ),
        bargap=0.25,
    )

    return fig.to_dict()